# Generated by Django 3.0.8 on 2022-03-19 17:12

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('user_phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(default='暂无', max_length=10, verbose_name='昵称')),
                ('animal_gender', models.CharField(choices=[('公', '公'), ('母', '母')], max_length=10, verbose_name='性别')),
                ('animal_age', models.IntegerField(default=0, help_text='年龄未知就填0', verbose_name='年龄')),
                ('animal_species', models.CharField(choices=[('猫', '猫'), ('狗', '狗')], max_length=10, verbose_name='猫/狗')),
                ('animal_status', models.CharField(choices=[('在野', '在野'), ('领养', '领养')], max_length=10, verbose_name='目前状态')),
                ('animal_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='动物描述')),
                ('animal_photo', models.ImageField(upload_to='photo/%Y_%m_%d', verbose_name='动物照片')),
                ('animal_created_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('animal_latest_edit_date', models.DateTimeField(auto_now=True, null=True, verbose_name='上次修改时间')),
                ('animal_adopter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='收养人')),
            ],
            options={
                'verbose_name': '动物管理',
                'verbose_name_plural': '动物管理',
            },
        ),
        migrations.CreateModel(
            name='Animal_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_species', models.CharField(default='猫', max_length=10, verbose_name='物种')),
                ('animal_type', models.CharField(max_length=10, verbose_name='品种')),
            ],
            options={
                'verbose_name': '品种',
                'verbose_name_plural': '品种管理',
            },
        ),
        migrations.CreateModel(
            name='Site_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Adopt_Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopt_date', models.DateField(auto_now_add=True, verbose_name='收养时间')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name='动物编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='收养人')),
            ],
            options={
                'verbose_name': '收养记录',
                'verbose_name_plural': '收养记录',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10, verbose_name='真实姓名')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('address', models.CharField(max_length=255, verbose_name='住址')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('creted_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='记录提交时间')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal', verbose_name='动物id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '申请记录',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal_Type', verbose_name='品种'),
        ),
    ]
