# Generated by Django 3.0.8 on 2022-03-19 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhongzhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaohao', models.IntegerField(default=0, verbose_name='编号')),
                ('zhushe', models.IntegerField(default=1, verbose_name='猪舍')),
                ('pinzhong', models.CharField(max_length=255, verbose_name='品种')),
                ('caishi', models.CharField(max_length=255, verbose_name='采食')),
                ('tiwen', models.CharField(max_length=11, verbose_name='体温')),
                ('xiwei', models.CharField(max_length=255, verbose_name='行为')),
                ('jingye', models.CharField(max_length=255, verbose_name='精液质量')),
                ('creted_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='记录提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理员')),
            ],
            options={
                'verbose_name': '种猪表',
                'verbose_name_plural': '种猪表',
            },
        ),
    ]
