# Generated by Django 3.0.8 on 2022-03-19 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_auto_20220319_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_adopt_animal',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='user_adopt_animal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Animal_Type',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='User_Adopt_Animal',
        ),
    ]
