# Generated by Django 3.0.8 on 2022-03-20 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_auto_20220320_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangzhiziliao',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entries1', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
