# Generated by Django 3.1 on 2022-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_auto_20220320_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='hangqing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shengfen', models.CharField(max_length=255, verbose_name='省份')),
                ('junjia', models.CharField(max_length=11, verbose_name='均价（元/公斤）')),
                ('zuori', models.CharField(max_length=255, verbose_name='较昨日')),
                ('quanguo', models.CharField(max_length=255, verbose_name='较全国')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
