# Generated by Django 3.1 on 2022-04-30 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0010_auto_20220430_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hangqing',
        ),
    ]
