# Generated by Django 3.1 on 2022-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0013_xinwen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siliao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=255, verbose_name='饲料名称')),
                ('kucun', models.CharField(max_length=255, verbose_name='库存')),
            ],
            options={
                'verbose_name': '饲料库存',
                'verbose_name_plural': '饲料库存',
            },
        ),
    ]
