# Generated by Django 3.1 on 2022-05-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0014_siliao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siliao',
            options={},
        ),
        migrations.AddField(
            model_name='zhongzhu',
            name='peizhong',
            field=models.CharField(default='已配种', max_length=255, verbose_name='是否已经配种'),
        ),
        migrations.AddField(
            model_name='zhongzhu',
            name='qiandai',
            field=models.CharField(default='1', max_length=255, verbose_name='前代种猪编号'),
        ),
        migrations.AddField(
            model_name='zhongzhu',
            name='yimiao',
            field=models.CharField(default='已接种', max_length=255, verbose_name='是否疫苗免疫'),
        ),
        migrations.AddField(
            model_name='zhongzhu',
            name='zaizhu',
            field=models.CharField(default='是', max_length=255, verbose_name='是否为仔猪'),
        ),
    ]
