# Generated by Django 3.1 on 2022-05-16 18:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0017_auto_20220512_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peizhong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField(default=0, verbose_name='编号')),
                ('jiluneirong', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='记录内容')),
            ],
        ),
        migrations.AlterField(
            model_name='zhongzhu',
            name='houdai',
            field=models.CharField(max_length=255, verbose_name='后代种猪编号'),
        ),
    ]
