# Generated by Django 3.1 on 2022-05-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0018_auto_20220516_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peizhong',
        ),
    ]
