# Generated by Django 3.1 on 2022-05-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0019_delete_peizhong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peizhong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField(default=0, verbose_name='编号')),
                ('jiluneirong', models.CharField(max_length=255, verbose_name='记录内容')),
            ],
        ),
    ]
