# Generated by Django 3.1 on 2022-05-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0020_peizhong'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hangqing',
        ),
        migrations.DeleteModel(
            name='Xinwen',
        ),
    ]
