# Generated by Django 3.1 on 2022-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0021_auto_20220526_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caijing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField(default=0, verbose_name='编号')),
                ('jiluneirong', models.CharField(max_length=255, verbose_name='记录内容')),
            ],
        ),
        migrations.CreateModel(
            name='Fenmian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField(default=0, verbose_name='编号')),
                ('jiluneirong', models.CharField(max_length=255, verbose_name='记录内容')),
            ],
        ),
        migrations.CreateModel(
            name='Renjian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField(default=0, verbose_name='编号')),
                ('jiluneirong', models.CharField(max_length=255, verbose_name='记录内容')),
            ],
        ),
        migrations.CreateModel(
            name='Xingweiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField(default=0, verbose_name='编号')),
                ('jiluneirong', models.CharField(max_length=255, verbose_name='记录内容')),
            ],
        ),
    ]
